---

#- hosts: all
#  tasks: [ ]

- hosts:  brokers, nodes
  roles:
   - role: common
  tags:
    - nodes
    - brokers

- hosts: brokers
  roles:
   - role: named
   - role: mongod
   - role: activemq
   - role: mcollective-client
   - role: broker
   - role: broker-plugins
   - role: web-console
  tags:
    - brokers

- hosts: nodes
  roles:
    - role: node
  tags:
    - nodes
