---

# group_vars/all Variables used in this yml
# mongo_db_name
# mongo_admin_user
# mongo_admin_passwd
# mongo_auth_user
# mongo_auth_passwd



- name: 3.1.0. Install the mongod server
  yum: pkg="{{item}}" state=latest
  with_items:
    - mongodb-server
    - mongodb
    - libmongodb

- name: 3.2.1. Setup MongoDB smallfiles option
  lineinfile: dest=/etc/mongodb.conf line='smallfiles=true'

- name: 3.2.2. Disable Authentication
  lineinfile: dest=/etc/mongodb.conf regexp='^auth ?=' state=absent

- name: Start MongoDB Server
  service: name=mongod state=started

# Next part doesn't seem to work unless server is restarted twice
- name: Restart MongoDB Server
  service: name=mongod state=restarted

- name: Create OpenShift broker user
  command: /usr/bin/mongo localhost/{{ mongo_db_name }} --eval 'db.addUser("{{ mongo_auth_user }}", "{{ mongo_auth_passwd }}")'

- name: Create OpenShift admin user
  command: /usr/bin/mongo localhost/admin --eval 'db.addUser("{{ mongo_admin_user }}", "{{ mongo_admin_passwd }}")'

- name: Stop MongoDB Server
  service: name=mongod state=stopped

- name: Enable Authenication
  lineinfile: dest=/etc/mongodb.conf line='auth = true'

- name: 3.3.0. Add MongoDB to iptables
  command: /usr/sbin/lokkit --port=27017:tcp  

- name: 3.4.0. Enable/Start MongoDB Server
  service: name=mongod state=restarted enabled=yes
