---

- name: 5.1.0. Install MCollective Client
  yum: pkg=ruby193-mcollective-client state=latest


- name: Configure mcollective client
  template: src=client.cfg.j2 dest=/opt/rh/ruby193/root/etc/mcollective/client.cfg
